services:
  games-web-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-minis}-web-1
    restart: unless-stopped
    environment:
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-auto}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-10r/s}
      - RATE_LIMIT_BURST=${RATE_LIMIT_BURST:-20}
      - CONTAINER_NAME=web-1
      - TZ=${TIMEZONE:-Europe/Zurich}
    volumes:
      # Static content - configurable between www and www-red
      - ./${CONTENT_DIR_1:-www}:/usr/share/nginx/html:ro
      # Logs with rotation
      - ./logs/web-1:/var/log/nginx
      # Nginx configuration
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik_public
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-0.5}'
          memory: ${MEMORY_LIMIT:-256M}
        reservations:
          cpus: '${CPU_RESERVATION:-0.1}'
          memory: ${MEMORY_RESERVATION:-64M}
    ports:
      - "${INTERNAL_PORT_1:-11888}:80"
    labels:
      # Traefik configuration for load balancing
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:-minis}.loadbalancer.server.port=80"

      # Main domain router (load balanced)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}.rule=Host(`${DOMAIN:-games.example.com}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}.tls.certresolver=${CERT_RESOLVER:-myresolver}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}.service=${COMPOSE_PROJECT_NAME:-minis}"

      # Additional domain aliases (load balanced)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-eiger.rule=Host(`${DOMAIN_ALIAS_1:-play.example.com}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-eiger.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-eiger.tls.certresolver=${CERT_RESOLVER:-myresolver}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-eiger.service=${COMPOSE_PROJECT_NAME:-minis}"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-www-eiger.rule=Host(`${DOMAIN_ALIAS_2:-www.play.example.com}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-www-eiger.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-www-eiger.tls.certresolver=${CERT_RESOLVER:-myresolver}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-www-eiger.service=${COMPOSE_PROJECT_NAME:-minis}"

      # Direct container access for testing (container 1)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-1.rule=Host(`${TEST_DOMAIN_1:-test1.games.example.com}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-1.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-1.tls.certresolver=${CERT_RESOLVER:-myresolver}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-1.service=${COMPOSE_PROJECT_NAME:-minis}-test-1"

      # Service definition for direct container 1 access
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:-minis}-test-1.loadbalancer.server.port=80"

  games-web-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-minis}-web-2
    restart: unless-stopped
    environment:
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-auto}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-10r/s}
      - RATE_LIMIT_BURST=${RATE_LIMIT_BURST:-20}
      - CONTAINER_NAME=web-2
      - TZ=${TIMEZONE:-Europe/Zurich}
    volumes:
      # Static content - configurable between www and www-red
      - ./${CONTENT_DIR_2:-www}:/usr/share/nginx/html:ro
      # Logs with rotation
      - ./logs/web-2:/var/log/nginx
      # Nginx configuration
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik_public
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-0.5}'
          memory: ${MEMORY_LIMIT:-256M}
        reservations:
          cpus: '${CPU_RESERVATION:-0.1}'
          memory: ${MEMORY_RESERVATION:-64M}
    ports:
      - "${INTERNAL_PORT_2:-11889}:80"
    labels:
      # Traefik configuration for load balancing
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:-minis}.loadbalancer.server.port=80"

      # Direct container access for testing (container 2)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-2.rule=Host(`${TEST_DOMAIN_2:-test2.games.example.com}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-2.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-2.tls.certresolver=${CERT_RESOLVER:-myresolver}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:-minis}-test-2.service=${COMPOSE_PROJECT_NAME:-minis}-test-2"

      # Service definition for direct container 2 access
      - "traefik.http.services.${COMPOSE_PROJECT_NAME:-minis}-test-2.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
